spring:
  application:
    name: ict-equipemnt
  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${MYSQLUSER}
      password: ${MYSQLPASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  cache:
    type: simple
    cache-names: users

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    max-age: ${CORS_MAX_AGE}

  frontend:
    reset-password-url: ${FRONTEND_RESET_PASSWORD_URL}